package io.openems.edge.hoymiles.hms_hmt.pvinverter;

import org.osgi.service.metatype.annotations.AttributeDefinition;
import org.osgi.service.metatype.annotations.ObjectClassDefinition;

import io.openems.edge.common.type.Phase.SingleOrAllPhase;

@ObjectClassDefinition(
        name = "PV-Inverter Hoymiles HMS/HMT",
        description = "SunSpec-based integration of Hoymiles HMS/HMT microinverters via DTU Pro in Modbus RTU mode.")
@interface Config {

    @AttributeDefinition(name = "Component-ID", description = "Unique ID of this Component")
    String id() default "pvInverter0";

    @AttributeDefinition(name = "Alias", description = "Human-readable name of this Component; defaults to Component-ID")
    String alias() default "";

    @AttributeDefinition(name = "Is enabled?", description = "Is this Component enabled?")
    boolean enabled() default true;

    @AttributeDefinition(name = "Read-Only mode", description = "In Read-Only mode no power-limitation commands are sent to the inverter")
    boolean readOnly() default true;

    @AttributeDefinition(name = "Use as production meter", description = ""
            + "If enabled, this inverter's power and energy are considered as PV production in SumImpl. "
            + "If disabled, values are only shown in UI and not included in production sums.")
    boolean useAsProductionMeter() default true;

    @AttributeDefinition(name = "Enable SetOutputPower", description = ""
            + "Enable writing output power limits to the inverter (SunSpec Model 123 or proprietary registers). "
            + "If disabled, no active power limitation commands are sent – the inverter runs with its internal settings.")
    boolean enableSetOutputPower() default false;

    @AttributeDefinition(name = "Modbus-ID", description = "ID of Modbus bridge.")
    String modbus_id() default "modbus0";

    @AttributeDefinition(name = "Modbus Unit-ID", description =
            "Modbus Unit-ID (slave address) of the Hoymiles inverter on the RS485 bus. "
          + "This is the RS485 address configured on the DTU Pro in SunSpec Modbus mode.")
    int modbusUnitId() default 1;

    @AttributeDefinition(name = "Phase", description = "On which phase is the inverter connected? For three-phase HMT use 'ALL'.")
    SingleOrAllPhase phase() default SingleOrAllPhase.ALL;

    @AttributeDefinition(name = "Number of PV inputs", description = "Number of PV module inputs of this inverter (2, 4 or 6).")
    int numberOfPvInputs() default 4;

    @AttributeDefinition(name = "Max DC power PV1 [W]", description = "Peak power of the PV module on input 1 in W. 0 = unused.")
    int maxPowerPv1_W() default 0;

    @AttributeDefinition(name = "Max DC power PV2 [W]", description = "Peak power of the PV module on input 2 in W. 0 = unused.")
    int maxPowerPv2_W() default 0;

    @AttributeDefinition(name = "Max DC power PV3 [W]", description = "Peak power of the PV module on input 3 in W. 0 = unused.")
    int maxPowerPv3_W() default 0;

    @AttributeDefinition(name = "Max DC power PV4 [W]", description = "Peak power of the PV module on input 4 in W. 0 = unused.")
    int maxPowerPv4_W() default 0;

    @AttributeDefinition(name = "Max DC power PV5 [W]", description = "Peak power of the PV module on input 5 in W. 0 = unused.")
    int maxPowerPv5_W() default 0;

    @AttributeDefinition(name = "Max DC power PV6 [W]", description = "Peak power of the PV module on input 6 in W. 0 = unused.")
    int maxPowerPv6_W() default 0;

    @AttributeDefinition(name = "Modbus target filter", description = "This is auto-generated by 'Modbus-ID'.")
    String Modbus_target() default "(enabled=true)";

    String webconsole_configurationFactory_nameHint() default "PV-Inverter Hoymiles HMS/HMT [{id}]";
}
