package io.openems.edge.deye.ess;

import org.osgi.service.metatype.annotations.AttributeDefinition;
import org.osgi.service.metatype.annotations.ObjectClassDefinition;
import io.openems.edge.deye.ess.DeyeOperationMode;


@ObjectClassDefinition(//
		name = "Deye.BatteryInverter", //
		description = "Implements the Deye Battery Inverter")
@interface Config {

	@AttributeDefinition(name = "Component-ID", description = "Unique ID of this Component")
	String id() default "ess0";

	@AttributeDefinition(name = "Alias", description = "Human-readable name of this Component; defaults to Component-ID")
	String alias() default "";

	@AttributeDefinition(name = "Is enabled?", description = "Is this Component enabled?")
	boolean enabled() default true;

	@AttributeDefinition(name = "Read-Only mode", description = "Enables Read-Only mode")
	boolean readOnlyMode() default false;

	@AttributeDefinition(name = "Modbus-ID", description = "ID of Modbus bridge.")
	String modbus_id() default "modbus0";

	@AttributeDefinition(name = "Modbus Unit-ID", description = "The Unit-ID of the Modbus device.")
	int modbusUnitId() default 1;

	// --- NEU: Hinzugefügte Konfigurationsparameter ---
	@AttributeDefinition(name = "Operation mode", description = "Initial operation mode of the inverter. Currently only STANDBY vs. non-STANDBY is implemented.")
	DeyeOperationMode operationMode() default DeyeOperationMode.REMOTE_CONTROLLED;
	
	@AttributeDefinition(name = "Nominal Power [W]", description = "Nominal AC power of the inverter (e.g., 15000 for 15kW). Used for percentage calculations.", defaultValue = "15000")
	int nominalPowerW();

	@AttributeDefinition(name = "Max Apparent Power [VA]", description = "Maximum apparent power capability of the inverter.", defaultValue = "16500") // Example default, adjust as needed
	int maxApparentPowerVA();

	@AttributeDefinition(name = "Min Reactive Power [var]", description = "Minimum reactive power setpoint capability.", defaultValue = "-10000") // Example default, adjust as needed
	int minReactivePowerVar();

	@AttributeDefinition(name = "Max Reactive Power [var]", description = "Maximum reactive power setpoint capability.", defaultValue = "10000") // Example default, adjust as needed
	int maxReactivePowerVar();

	@AttributeDefinition(name = "Net Battery Capacity [Wh]", description = "Usable capacity of the connected battery.", defaultValue = "10000") // Example default, adjust as needed
	int netCapacityWh();
	// --- ENDE: Hinzugefügte Konfigurationsparameter ---

	// --- Umbenannter Parameter ---
	@AttributeDefinition(name = "Power Limit on Overtemperature [W]", description = "Absolute power limit (charge/discharge in W) applied when overtemperature is detected. Set to 0 to disable this specific limit override.", defaultValue = "2000")
	int powerLimitOnOvertemperatureW();
	// --- ENDE: Umbenannter Parameter ---

	@AttributeDefinition(name = "Modbus target filter", description = "This is auto-generated by 'Modbus-ID'.")
	String Modbus_target() default "(enabled=true)";

	// --- Surplus Feed-In Parameter (unverändert) ---
	@AttributeDefinition(name = "Surplus Feed-In: State-of-Charge limit", description = "Start Surplus-feed-in if State-of-Charge is bigger than this limit")
	int surplusFeedInSocLimit() default 90;

	@AttributeDefinition(name = "Surplus Feed-In: Allowed-Charge-Power limit", description = "Start Surplus-feed-in if Charge-Power is smaller than this limit. (Needs to set negative)")
	int surplusFeedInAllowedChargePowerLimit() default -8_000;

	@AttributeDefinition(name = "Surplus Feed-In: Increase Power by percentage", description = "1.1 for 10 %")
	double surplusFeedInIncreasePowerFactor() default 1.1;

	@AttributeDefinition(name = "Surplus Feed-In: Max increase Power", description = "")
	int surplusFeedInMaxIncreasePowerFactor() default 2_000;

	@AttributeDefinition(name = "Surplus Feed-In: Off Time", description = "The time to stop grid feed in.")
	String surplusFeedInOffTime() default "17:00:00";

	@AttributeDefinition(name = "Surplus Feed-In: PV-Limit on PowerDecreaseCausedByOvertemperature", description = "")
	int surplusFeedInPvLimitOnPowerDecreaseCausedByOvertemperature() default 5_000;
	// --- ENDE: Surplus Feed-In Parameter ---

	String webconsole_configurationFactory_nameHint() default "Deye Battery Inverter [{id}]";
}